### ISSUE TITLE
If there is a "." in the source folder name the transform fails

### ISSUE THREAD

**Issue by gperrego** [RegionOrebroLan/PowerShell-Transforming#2]
I'm not sure why but when the Source folder contains a "." the Powershell New-PackageTransform fails.  Is there some way to escape this or?

This works:
New-PackageTransform -Source "C:\Temp\MyFolder" -Destination $Destination -FileToTransformPatterns $FileToTransformPatterns -TransformationNames $TransformationNames

This Fails
New-PackageTransform -Source "C:\Temp\My.Folder" -Destination $Destination -FileToTransformPatterns $FileToTransformPatterns -TransformationNames $TransformationNames

**Comment by HansKindberg** [comment]
Hi @gperrego 

Thank you for reporting it. I will have a look. I guess its a bug.

It may take a while but I will be back.

Regards Hans

**Comment by HansKindberg** [comment]
Created bug-issue in the right repository: https://github.com/RegionOrebroLan/.NET-Transforming/issues/1

**Comment by HansKindberg** [comment]
Fixed: https://github.com/RegionOrebroLan/PowerShell-Transforming/commit/2610ed4e4dc4f60e486b52daec9465f1fe9ac860

@gperrego 
There is now a new version, 1.0.1, at PSGallery. Please try it.
